Parameters:
  AvailabilityZones:
    Description: List of Availability Zones
    Type: "List<AWS::EC2:AvailabilityZone::Name>"
  PublicSubnet1:
    Description: CIDR block for public subnet 1 
    Type: String
    AllowedPattern: >-
    ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.0.128.0/20
    ConstraintDescription: CIDR block paramater must be in the form x.x.x.x/16-28
#  PrivateSubnet1:
#    Description: CIDR block for private subnet 1
#    Type: String 
#    AllowedPattern: >-
#    ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    Default: 10.0.0.0/19
#    ConstraintDescription: CIDR block parameter must be in the form of x.x.x.x/16-28
Resources:
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}
  attachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCID
      InternetGatewayId: !Ref myInternetGateway
  publicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCID
      CidrBlock: !Ref PublicSubnet1
      AvailabilityZone: !Ref AvailabilityZone
 #privateSubnet1:
 #   Type: AWS::EC2::Subnet
 #   Properties:
 #     VpcId: !Ref VPCID
 #     CidrBlock: !Ref PrivateSubnet1
 #     AvailabilityZone: !Ref AvailabilityZone
  publicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
  publicSubnetRoute:
    DependsOn: myInternetGateway
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref publicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref myInternetGateway
  subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnet1
      RouteTableId: !Ref publicSubnetRouteTable
  
